experiment: 'InfillingKicksAndSnares'
batch_size: 32
d_model: 256
dim_feedforward: 512
dropout: 0.30
optimizer_algorithm: 'sgd'
learning_rate: 0.089
n_heads: 2
num_encoder_decoder_layers: 6
epochs: 1500
encoder_only: 1
hit_loss_penalty: 0.73
load_model: Null
# params from efficient-sweep-9