experiment: 'InfillingKicksAndSnares'
batch_size: 32
d_model: 256
dim_feedforward: 2048
dropout: 0.30
optimizer_algorithm: 'sgd'
learning_rate: 0.089
n_heads: 2
num_encoder_decoder_layers: 6
epochs: 400
encoder_only: 1
hit_loss_penalty: 0.73
load_model: Null
# params from efficient-sweep-9, but with dim_feedforward at 2048 instead of 512