experiment: 'InfillingRandomLow'
batch_size: 32
d_model: 256
dim_feedforward: 2048
dropout: 0.16
optimizer_algorithm: 'sgd'
learning_rate: 0.070
n_heads: 2
num_encoder_decoder_layers: 8
epochs: 3000
encoder_only: 1
hit_loss_penalty: 0.46
load_model: Null
notes: 'same parameters as InfillingKicksAndSnares'